# /etc/docker/compose/kafka-manager/docker-compose.yml
version: '3.6'
services:
  kafka_manager:
    image: hlebalbau/kafka-manager:stable
    ports:
      - "9000:9000"
    environment:
      ZK_HOSTS: "172.31.1.1:2181,172.31.17.1:2181,172.31.33.1:2181"
      APPLICATION_SECRET: "random-secret"
    command: -Dpidfile.path=/dev/null